
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorStatPy;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PT = 14;
  public static final int wBREAK = 34;
  public static final int PAR_DER = 4;
  public static final int wPrint = 29;
  public static final int POR = 17;
  public static final int wFOR = 35;
  public static final int RELACIONES = 43;
  public static final int ENTERO = 20;
  public static final int wELSE = 31;
  public static final int wWHILE = 36;
  public static final int wDO = 37;
  public static final int DOSPT = 7;
  public static final int identificador = 48;
  public static final int varCHAR = 24;
  public static final int NOT = 47;
  public static final int AND = 45;
  public static final int IGUAL = 44;
  public static final int varDOUBLE = 23;
  public static final int OR = 46;
  public static final int varINT = 22;
  public static final int COMS = 5;
  public static final int wMain = 28;
  public static final int DIV = 18;
  public static final int UMENOS = 19;
  public static final int EOF = 0;
  public static final int DECIMAL = 21;
  public static final int COMD = 6;
  public static final int varBOOL = 25;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int wVoid = 27;
  public static final int MENOS = 16;
  public static final int wTITULOY = 42;
  public static final int wTITULOX = 41;
  public static final int wCASE = 33;
  public static final int PAR_IZQ = 3;
  public static final int LLI = 8;
  public static final int wIF = 30;
  public static final int wTITULO = 38;
  public static final int LLC = 9;
  public static final int wEJEX = 39;
  public static final int DOLLAR = 10;
  public static final int wVALORES = 40;
  public static final int CORI = 12;
  public static final int PTCOMA = 2;
  public static final int CORD = 13;
  public static final int wSWITCH = 32;
  public static final int MAS = 15;
  public static final int varSTRING = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PAR_IZQ",
  "PAR_DER",
  "COMS",
  "COMD",
  "DOSPT",
  "LLI",
  "LLC",
  "DOLLAR",
  "COMA",
  "CORI",
  "CORD",
  "PT",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "UMENOS",
  "ENTERO",
  "DECIMAL",
  "varINT",
  "varDOUBLE",
  "varCHAR",
  "varBOOL",
  "varSTRING",
  "wVoid",
  "wMain",
  "wPrint",
  "wIF",
  "wELSE",
  "wSWITCH",
  "wCASE",
  "wBREAK",
  "wFOR",
  "wWHILE",
  "wDO",
  "wTITULO",
  "wEJEX",
  "wVALORES",
  "wTITULOX",
  "wTITULOY",
  "RELACIONES",
  "IGUAL",
  "AND",
  "OR",
  "NOT",
  "identificador"
  };
}

