
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorStatPy;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 8;
  public static final int DECIMAL = 12;
  public static final int varCHAR = 16;
  public static final int wVoid = 22;
  public static final int LLI = 20;
  public static final int UMENOS = 13;
  public static final int POR = 9;
  public static final int LLC = 21;
  public static final int varINT = 14;
  public static final int EOF = 0;
  public static final int DIV = 10;
  public static final int PAR_IZQ = 3;
  public static final int error = 1;
  public static final int PAR_DER = 4;
  public static final int COR_IZQ = 5;
  public static final int varDOUBLE = 15;
  public static final int varBOOL = 17;
  public static final int COR_DER = 6;
  public static final int ENTERO = 11;
  public static final int varSTRING = 18;
  public static final int wMain = 23;
  public static final int VAR = 19;
  public static final int MAS = 7;
  public static final int PTCOMA = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PAR_IZQ",
  "PAR_DER",
  "COR_IZQ",
  "COR_DER",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "ENTERO",
  "DECIMAL",
  "UMENOS",
  "varINT",
  "varDOUBLE",
  "varCHAR",
  "varBOOL",
  "varSTRING",
  "VAR",
  "LLI",
  "LLC",
  "wVoid",
  "wMain"
  };
}

